import { describe, expect, it } from 'vitest';

import {
  buildCuratedSmokeCollection,
  buildGeneratedSmokeCollection
} from '../src/postman/collection-transform.js';
import type { FlowDefinition, ResolvedRequest } from '../src/types.js';

/**
 * Bootstrap owns the canonical Smoke collection's identity: it elects/adopts a
 * final by exact `info.name` plus the durable branch marker carried in
 * `info.description`. smoke-flow refreshes that collection's body in place, so
 * it must never rewrite either identity field. When it does, the next bootstrap
 * run sees no same-name/same-marker final to adopt, imports a fresh collection,
 * and the old one is orphaned along with the monitor bound to its UID.
 */

const CANONICAL_NAME = '[PROJECT] [Smoke] Example Fixture API';
const CANONICAL_DESCRIPTION = [
  'Generated by the Postman onboarding actions.',
  '',
  '<!-- postman-asset-marker:{"branch":"project/drum-api","tier":"channel","createdAt":"2026-07-27T00:00:00.000Z"} -->'
].join('\n');

function canonicalCollection(): Record<string, unknown> {
  return {
    info: {
      name: CANONICAL_NAME,
      description: CANONICAL_DESCRIPTION,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    item: []
  };
}

/** What Postman's spec generator returns for the temp collection. */
function generatedCollection(): Record<string, unknown> {
  return {
    info: {
      name: '[Smoke][Temp] Example Fixture API',
      description: 'Generated from OpenAPI spec by Postman.',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    item: [
      {
        name: 'createPayment',
        request: { method: 'POST', url: { raw: 'https://example.test/payments' } }
      },
      {
        name: 'getPaymentById',
        request: { method: 'GET', url: { raw: 'https://example.test/payments/:id' } }
      }
    ]
  };
}

const flow: FlowDefinition = {
  name: 'Example Fixture API happy path',
  type: 'smoke',
  steps: [
    { stepKey: 'create-payment-1', operationId: 'createPayment', bindings: [], extract: [] },
    { stepKey: 'get-payment-by-id-2', operationId: 'getPaymentById', bindings: [], extract: [] }
  ]
};

const resolvedRequests: ResolvedRequest[] = [
  {
    step: flow.steps[0]!,
    item: {
      name: 'createPayment',
      request: { method: 'POST', url: { raw: 'https://example.test/payments' } }
    },
    matchTier: 'operationId'
  } as unknown as ResolvedRequest,
  {
    step: flow.steps[1]!,
    item: {
      name: 'getPaymentById',
      request: { method: 'GET', url: { raw: 'https://example.test/payments/:id' } }
    },
    matchTier: 'operationId'
  } as unknown as ResolvedRequest
];

function info(collection: Record<string, unknown>): Record<string, unknown> {
  return collection.info as Record<string, unknown>;
}

describe('canonical Smoke identity preservation', () => {
  it('curated refresh keeps the canonical collection name', () => {
    const { collection } = buildCuratedSmokeCollection(
      generatedCollection(),
      flow,
      resolvedRequests,
      undefined,
      true,
      { canonicalCollection: canonicalCollection() }
    );

    expect(info(collection).name).toBe(CANONICAL_NAME);
  });

  it('curated refresh keeps the canonical branch marker description', () => {
    const { collection } = buildCuratedSmokeCollection(
      generatedCollection(),
      flow,
      resolvedRequests,
      undefined,
      true,
      { canonicalCollection: canonicalCollection() }
    );

    expect(info(collection).description).toBe(CANONICAL_DESCRIPTION);
  });

  it('curated refresh still uses the flow name when no canonical collection is supplied', () => {
    const { collection } = buildCuratedSmokeCollection(
      generatedCollection(),
      flow,
      resolvedRequests,
      undefined,
      true
    );

    expect(info(collection).name).toBe(`[Smoke] ${flow.name}`);
  });

  it('uncurated refresh keeps the canonical branch marker description', () => {
    const { collection } = buildGeneratedSmokeCollection(generatedCollection(), undefined, {
      collectionName: CANONICAL_NAME,
      canonicalCollection: canonicalCollection()
    });

    expect(info(collection).name).toBe(CANONICAL_NAME);
    expect(info(collection).description).toBe(CANONICAL_DESCRIPTION);
  });

  it('does not invent a description when the canonical collection has none', () => {
    const bare = canonicalCollection();
    delete (bare.info as Record<string, unknown>).description;

    const { collection } = buildCuratedSmokeCollection(
      generatedCollection(),
      flow,
      resolvedRequests,
      undefined,
      true,
      { canonicalCollection: bare }
    );

    expect(info(collection).name).toBe(CANONICAL_NAME);
    expect(info(collection).description).toBeUndefined();
  });
});
