export const smokeFlowActionContract = {
  inputs: {
    'project-name': { required: true },
    'workspace-id': { required: true },
    'spec-id': { required: true },
    'smoke-collection-id': { required: true },
    'flow-path': { required: false },
    'flow-mode': { required: false, default: 'auto' },
    'flow-allow-delete': { required: false, default: 'false' },
    'postman-api-key': { required: false },
    'postman-region': { required: false, default: 'us' },
    'auth-config-json': { required: false },
    'auth-plan-path': { required: false },
    'secrets-resolver': { required: false, default: 'none' },
    'secrets-resolver-enabled': { required: false },
    'spec-path': { required: false },
    'debug-dump-path': { required: false },
    'collection-sync-mode': { required: false, default: 'refresh' },
    'postman-access-token': { required: false },
    'fail-on-flow-warning': { required: false, default: 'false' },
    'keep-temp-collection-on-failure': { required: false, default: 'false' },
    'temp-collection-prefix': { required: false, default: '[Smoke][Temp]' },
    'persist-derived-flow': { required: false, default: 'true' },
    'team-id': { required: false },
    'branch-strategy': { required: false, default: 'legacy' },
    'canonical-branch': { required: false },
    'channels': { required: false }
  },
  outputs: {
    'smoke-collection-id': {},
    'flow-apply-status': {},
    'flow-apply-summary-json': {},
    'temporary-smoke-collection-id': {},
    'flow-step-count': {},
    'resolved-operation-count': {},
    'applied-binding-count': {},
    'applied-extract-count': {},
    'assertion-count': {},
    'derived-flow-path': {},
    'sync-status': {},
    'branch-decision': {}
  }
} as const;
